

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # mongodb:
  #   image: mongo:7
  #   container_name: leaveease-mongodb-new
  #   restart: always
  #   ports:
  #     - "27017:27017"